import { ChakraProvider } from "@chakra-ui/react";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ChakraProvider>
        <body>{children}</body>
      </ChakraProvider>
    </html>
  );
}
